
import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Plus } from "lucide-react";

interface MechanicFormProps {
  onMechanicAdded: () => void;
}

const MechanicForm = ({ onMechanicAdded }: MechanicFormProps) => {
  const [addDialogOpen, setAddDialogOpen] = useState(false);
  const [formData, setFormData] = useState({
    name: "",
    phone: "",
    email: "",
  });
  const [formLoading, setFormLoading] = useState(false);
  const { toast } = useToast();

  const handleAddMechanic = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormLoading(true);

    try {
      const { data: user } = await supabase.auth.getUser();
      if (!user.user) throw new Error("User not authenticated");

      const { data: garage } = await supabase
        .from("garages")
        .select("id")
        .eq("owner_id", user.user.id)
        .single();

      if (!garage) throw new Error("Garage not found");

      // Insert without mechanic_id - it will be auto-generated by the trigger
      const insertData = {
        garage_id: garage.id,
        name: formData.name.trim(),
        phone: formData.phone.trim() || null,
        email: formData.email.trim() || null,
      } as any;

      const { error } = await supabase
        .from("mechanics")
        .insert(insertData);

      if (error) throw error;

      toast({
        title: "Success",
        description: "Mechanic added successfully",
      });

      setFormData({ name: "", phone: "", email: "" });
      setAddDialogOpen(false);
      onMechanicAdded();
    } catch (error) {
      console.error("Error adding mechanic:", error);
      toast({
        title: "Error",
        description: "Failed to add mechanic",
        variant: "destructive",
      });
    } finally {
      setFormLoading(false);
    }
  };

  return (
    <Dialog open={addDialogOpen} onOpenChange={setAddDialogOpen}>
      <DialogTrigger asChild>
        <Button>
          <Plus className="h-4 w-4 mr-2" />
          Add Mechanic
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Add New Mechanic</DialogTitle>
          <DialogDescription>
            Add a new mechanic to your garage. A unique mechanic ID will be generated automatically.
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleAddMechanic} className="space-y-4">
          <div>
            <Label htmlFor="name">Name *</Label>
            <Input
              id="name"
              value={formData.name}
              onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              placeholder="Enter mechanic's full name"
              required
            />
          </div>
          <div>
            <Label htmlFor="phone">Phone</Label>
            <Input
              id="phone"
              value={formData.phone}
              onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
              placeholder="Enter phone number"
            />
          </div>
          <div>
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              value={formData.email}
              onChange={(e) => setFormData({ ...formData, email: e.target.value })}
              placeholder="Enter email address"
            />
          </div>
          <div className="flex justify-end gap-2">
            <Button
              type="button"
              variant="outline"
              onClick={() => setAddDialogOpen(false)}
              disabled={formLoading}
            >
              Cancel
            </Button>
            <Button type="submit" disabled={formLoading}>
              {formLoading ? "Adding..." : "Add Mechanic"}
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default MechanicForm;
